version: 2.1

orbs:
  node: circleci/node@5.0.0  # Use the latest version of the node orb

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
                - feature/init-projects

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0  # Use the latest version of the Node.js image
    steps:
      - checkout
      - node/install:
          node-version: '18.x'
      - run:
          name: Change to Project Directory
          command: cd kwadra-web-client
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: ./kwadra-web-client
      - run:
          name: Build
          command: npm run build
          working_directory: ./kwadra-web-client

  deploy:
    docker:
      - image: cimg/node:18.0  # Use the latest version of the Node.js image
    steps:
      - checkout
      - run:
          name: Set up SSH
          command: |
            mkdir -p ~/.ssh/
            echo $SSH_PRIVATE_KEY > ~/.ssh/githubactions
            chmod 600 ~/.ssh/githubactions
            ssh-keyscan -p 711 $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Server
          command: |
            ssh -p 711 $SSH_USER@$SSH_HOST "cd /home/nikoden/kwadra-web-client && git pull && npm install && npm run build && pm2 restart all"
